### ISSUE TITLE
AssertionError: Keyword argument not understood: padding

### ISSUE THREAD

**Issue by tangxiangru** [NPoe/neural-nlp-explanation-experiment#4]
(python-thn) [txr@localhost SRC]$ python main.py train newsgroup CNN
Using TensorFlow backend.
Loading from ../Inputs/newsgroup/embeddings
Loading from ../Inputs/newsgroup/worddict
Loading from ../Inputs/newsgroup/classdict
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    train(architecture, corpus)
  File "main.py", line 25, in train
    model.build()
  File "/home/txr/neural-nlp-explanation-experiment/HybridDocuments/SRC/task_methods.py", line 76, in build
    input_shape = (None, self.corpus.EMB_SIZE)))
  File "/home/txr/anaconda3/envs/python-thn/lib/python3.4/site-packages/keras/layers/convolutional.py", line 112, in __init__
    super(Convolution1D, self).__init__(**kwargs)
  File "/home/txr/anaconda3/envs/python-thn/lib/python3.4/site-packages/keras/engine/topology.py", line 307, in __init__
    assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
AssertionError: Keyword argument not understood: padding

**Comment by NPoe** [comment]
https://github.com/NPoe/neural-nlp-explanation-experiment/issues/2
