### ISSUE TITLE
I used your keras, but a bug exsits

### ISSUE THREAD

**Issue by tangxiangru** [NPoe/neural-nlp-explanation-experiment#5]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from task_methods import *
  File "/home/txr/neural-nlp-explanation-experiment/SRC/task_methods.py", line 10, in <module>
    from keras.layers import *
ImportError: No module named 'keras.layers'

**Comment by NPoe** [comment]
How did you install the keras fork? I have put instructions in a comment of another issue that you opened: https://github.com/NPoe/neural-nlp-explanation-experiment/issues/2
